# Generated by Django 2.2.16 on 2022-05-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20220513_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipe/images', verbose_name='картинка'),
        ),
    ]
