# Generated by Django 2.2.16 on 2022-05-17 01:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0007_auto_20220517_0033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shopping_Cart',
            new_name='ShoppingCart',
        ),
    ]
